### ISSUE TITLE
issue when testing pyqz

### ISSUE THREAD

**Issue by ami88** [fpavogt/pyqz#1]
Hi,

I have a MacBook Pro with OS X El Capitan (10.11.5). I installed pyqz and added in my .bashrc

export PYTHONPATH=$PYTHONPATH:/Users/mypath/pyqz-0.8.0/src

I am trying to run the tests for pyqz. I tried:

> run pyqz_check.py

but my computer does not recognize the command "run". Also I google a bit and I cannot figure out how to install something like that.
Then, just to try something else, I made pyqz_check.py executable and I typed

> ./pyqz_check.py

that prints plenty of things on the screen and the following errors at the end:

By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1294.
./pyqz_checks.py: line 36: syntax error near unexpected token `('
./pyqz_checks.py: line 36: `def interpgridnodes(Pk = 5.0, kappa = np.inf, struct='pp', sampling = 1):'

Any idea about how to fix this?

Ana

**Comment by fpavogt** [comment]
Hi Ana, 

pyqz is a python module. The pyqz_check.py is a python script, and is intended to be run inside a python shell, which can usually be started by typing: 

ipython --pylab

in a terminal. Once inside the python shell, you can then type the command "run pyqz_check.py".

Closing this issue as it is not pyqz-related. If something else shows up once you run the script, don't hesitate to open a new issue !
