### ISSUE TITLE
error when running the example for pyqz.get_global_qz

### ISSUE THREAD

**Issue by ami88** [fpavogt/pyqz#3]
Hello again,

I am going through the examples in Running pyqz I and Running pyqz II. When typing this one:

pyqz.get_global_qz(np.array([[ 1.00e+00, 5.00e-02, 2.38e+00, 1.19e-01, 5.07e+00, 2.53e-01,
                               5.67e-01, 2.84e-02, 5.11e-01, 2.55e-02, 2.88e+00, 1.44e-01]]),
                   ['Hb','stdHb','[OIII]','std[OIII]','[OII]+','std[OII]+',
                    '[NII]','std[NII]','[SII]+','std[SII]+','Ha','stdHa'],
                   ['[NII]/[SII]+;[OIII]/Hb','[NII]/[OII]+;[OIII]/[SII]+'],
                   ids = ['NGC_1234'],
                   KDE_method = 'multiv',
                   KDE_qz_sampling = 201j,
                   struct = 'pp',
                   sampling = 1,
                   verbose = True)

I get an AttributeError that I don't know how to fix (I will copy and paste below). Any hint about how to fix this?

Best regards,

Ana

====================
.....
--> Received 1 spectrum ...
--> Dealing with them one at a time ... be patient now !
    (no status update until I am done ...)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-fcfbe5f031cb> in <module>()
      9                    struct = 'pp',
     10                    sampling = 1,
---> 11                    verbose = True)

/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.pyc in get_global_qz(data, data_cols, which_grids, ids, qzs, Pk, kappa, struct, sampling, error_pdf, srs, flag_level, KDE_method, KDE_qz_sampling, KDE_do_singles, KDE_pickle_loc, verbose, nproc)
   1175                 print '    (no status update until I am done ...)'
   1176 
-> 1177             results = map(get_global_qz_singlespec, jobs)
   1178 
   1179         else:

/Users/ami/Codigos/pyqz-0.8.0/src/pyqz.pyc in get_global_qz_singlespec((j, final_cols, data, data_cols, which_grids, ids, qzs, Pk, kappa, struct, sampling, error_pdf, srs, flag_level, KDE_method, KDE_qz_sampling, KDE_do_singles, KDE_pickle_loc, verbose))
    904     for qz in qzs:
    905 
--> 906         mean_qz = stats.stats.nanmean(final_data[np.array(which_qz[qz])])
    907         std_qz = stats.stats.nanstd(final_data[np.array(which_qz[qz])], 
    908                                     bias=True)

AttributeError: 'module' object has no attribute 'nanmean'

**Comment by fpavogt** [comment]
Yes, I think I know. This is related to numpy 1.12, in which array elements can only be called using integer. I will need to revise the entire code to fix this. In the mean time, it should work if you were to downgrade your numpy version to 1.11. Not the most ideal, but the fastest way to get this running I fear ...

**Comment by fpavogt** [comment]
Fixed with commit #4c7722289b884a76a71248e49a33a7ed677e7678.
